apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: 2024-austin/registry/clusters/cluster-newyork/cert-issuers
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
