apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frankfurt-linkerd-smi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: linkerd-smi
    repoURL: https://linkerd.github.io/linkerd-smi
    targetRevision: 1.0.4
  destination:
    name: frankfurt
    namespace: linkerd-smi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
