apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frankfurt-linkerd-multicluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: linkerd-multicluster
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 30.11.9
  destination:
    name: frankfurt
    namespace: linkerd-multicluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
