apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: south-metaphor-development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate
    path: 2024-austin/registry-test/apps/development/metaphor
    targetRevision: east-west
    helm:
      valueFiles:
        - south-values.yaml
  destination:
    name: south
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true