apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dublin-cloudflare-cloudflare-origin-ca-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer
    chart: origin-ca-issuer
    targetRevision: v0.5.2
    helm:
      values: |-
        global:
          rbac:
            create: true
        controller:
          image:
            repository: cloudflare/origin-ca-issuer
            tag: v0.6.1
            pullPolicy: Always
  destination:
    name: dublin
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true