apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dublin-cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: 2024-austin/registry/clusters/dublin/cert-issuers
    targetRevision: cloudflare
  destination:
    name: dublin
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
