# apiVersion: tf.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: dev-green
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
# spec:
#   configuration: |
#       terraform {
#         backend "kubernetes" {
#           secret_suffix     = "providerconfig-civo-lon1"
#           namespace         = "crossplane-system"
#           in_cluster_config = true
#         }
#         required_providers {
#           civo = {
#             source = "civo/civo"
#           }
#           kubernetes = {
#             source = "hashicorp/kubernetes"
#             version = "2.23.0"
#           }
#         }
#       }
#       provider "civo" {
#         region = "lon1"
#       }
#   credentials:
#   - filename: gen-nothing
#     source: None
#     secretRef:
#       namespace: crossplane-system
#       name: crossplane-secrets
#       key: CIVO_TOKEN
