metaphor:
  annotations:
    linkerd.io/inject: "enabled"
  labels:
    mirror.linkerd.io/exported: "true"
  image:
    tag: 0.1.0-2024-navigate-austin
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-south.civonetes.com
        paths:
          - path: /
            pathType: Prefix
      - host: metaphor.civonetes.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor.civonetes.com
          - metaphor-south.civonetes.com
  metaphor:
    host: https://metaphor-south.civonetes.com/api
    console: https://kubefirst.civonetes.com
  useExternalSecret: false
  configs:
    configOne: south-cluster-override-one
    configTwo: south-cluster-override-two
