apiVersion: v1
kind: ServiceAccount
metadata:
  name: south-k8s-toolkit-eso
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: south-k8s-toolkit-eso
  namespace: argocd
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: south-k8s-toolkit-eso
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: south-k8s-toolkit-eso
subjects:
  - kind: ServiceAccount
    name: south-k8s-toolkit-eso
    namespace: argocd
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '35'
  name: south-wait-upstream-linkerd-identity
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=identity
            - --use-kubeconfig-in-cluster
            - "false"
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.1.2
          imagePullPolicy: IfNotPresent
          name: wait
          env:
            - name: KUBECONFIG
              value: /root/.kube/kubeconfig
          volumeMounts:
            - mountPath: /root/.kube
              name: kubeconfig
      restartPolicy: OnFailure
      serviceAccountName: south-k8s-toolkit-eso
      volumes:
        - name: kubeconfig
          secret:
            secretName: south-kubeconfig
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '35'
  name: south-wait-proxy-injector
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=proxy-injector
            - --use-kubeconfig-in-cluster
            - "false"
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.1.2
          imagePullPolicy: IfNotPresent
          name: wait
          env:
            - name: KUBECONFIG
              value: /root/.kube/kubeconfig
          volumeMounts:
            - mountPath: /root/.kube
              name: kubeconfig
      restartPolicy: OnFailure
      serviceAccountName: south-k8s-toolkit-eso
      volumes:
        - name: kubeconfig
          secret:
            secretName: south-kubeconfig
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '35'
  name: south-wait-destination
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=destination
            - --use-kubeconfig-in-cluster
            - "false"
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.1.2
          imagePullPolicy: IfNotPresent
          name: wait
          env:
            - name: KUBECONFIG
              value: /root/.kube/kubeconfig
          volumeMounts:
            - mountPath: /root/.kube
              name: kubeconfig
      restartPolicy: OnFailure
      serviceAccountName: south-k8s-toolkit-eso
      volumes:
        - name: kubeconfig
          secret:
            secretName: south-kubeconfig
