apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: south-linkerd-multicluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    chart: linkerd-multicluster
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 30.11.9
  destination:
    name: south
    namespace: linkerd-multicluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
