apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: dev-green-infrastructure
spec:
  providerConfigRef: 
    name: dev-green
  forProvider:
    source: Remote
    module: git::https://github.com/kubefirst/navigate.git//terraform/modules/cluster?ref=main
    vars:
    - key: cluster_name
      value: dev-green
    - key: node_count
      value: "3"
    - key: node_type
      value: "g4s.kube.medium"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dev-green-infrastructure-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: wait
        image: bitnami/kubectl:1.25.12
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl wait --for=jsonpath='{.status.conditions[0].status}'='True' workspace/dev-green-infrastructure; do echo "waiting for cluster to provision"; sleep 5; done
      restartPolicy: Never
  backoffLimit: 1
