apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-fred-cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: sync-waves/registry/clusters/cluster-fred/cert-issuers
    targetRevision: HEAD
  destination:
    name: cluster-fred
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
