apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: denver-infrastructure
spec:
  providerConfigRef: 
    name: denver
  forProvider:
    source: Remote
    module: git::https://github.com/kubefirst/navigate.git//2024-austin/terraform/modules/cluster-cloudflare?ref=cloudflare
    vars:
    - key: cluster_name
      value: denver
    - key: node_count
      value: "3"
    - key: node_type
      value: "g4s.kube.medium"
