apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-newyork-linkerd-link-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate
    path: 2024-austin/registry/clusters/cluster-newyork/linkerd/components/multicluster/link
    targetRevision: HEAD
  destination:
    name: cluster-newyork
    namespace: linkerd-multicluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
