metaphor:
  annotations:
    linkerd.io/inject: "enabled"
  labels:
    mirror.linkerd.io/exported: "true"
  image:
    tag: 0.1.0-2024-navigate-austin
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-frankfurt.kubefirst.boo
        paths:
          - path: /
            pathType: Prefix
      - host: metaphor.kubefirst.boo
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor.kubefirst.boo
          - metaphor-frankfurt.kubefirst.boo
  metaphor:
    host: https://metaphor-frankfurt.kubefirst.boo/api
    console: https://kubefirst.kubefirst.boo
  
  useExternalSecret: false
  configs:
    configOne: frankfurt-cluster-override-one
    configTwo: frankfurt-cluster-override-two
