apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: austin-linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.8.0
  destination:
    name: austin
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
