apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-newyork-linkerd-viz-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: git@github.com:kgetpods-biz/gitops.git
    path: 2024-austin/registry/clusters/cluster-newyork/linkerd/components/viz
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
