metaphor:
  annotations: |
    linkerd.io/inject: "enabled"
  labels: |
    mirror.linkerd.io/exported: "true"
  image:
    repository: ghcr.io/kgetpods-biz/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-development.kgetpods.biz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-development.kgetpods.biz
  metaphor:
    host: https://metaphor-development.kgetpods.biz/api
    console: https://kubefirst.kgetpods.biz

  clusterSecretStoreName: blue-vault-kv-secret
  configs:
    configOne: blue-cluster-override-one
    configTwo: blue-cluster-override-two