metaphor:
  annotations: |
    linkerd.io/inject: "enabled"
  labels: |
    mirror.linkerd.io/exported: "true"
  image:
    tag: 0.1.0-20204-navigate-austin
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-newyork.freegitopsmagic.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-newyork.freegitopsmagic.com
  metaphor: # do we need these two urls?
    host: https://metaphor-newyork.freegitopsmagic.com/api
    console: https://kubefirst.freegitopsmagic.com
  
  useExternalSecret: false

  # clusterSecretStoreName: newyork-vault-kv-secret
  configs:
    configOne: newyork-cluster-override-one
    configTwo: newyork-cluster-override-two
