metaphor:
  annotations:
    linkerd.io/inject: "enabled"
  labels:
    mirror.linkerd.io/exported: "true"
  image:
    tag: 0.1.0-2024-navigate-austin
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-london.gitopsmagic.com
        paths:
          - path: /
            pathType: Prefix
      # - host: metaphor.gitopsmagic.com
      #   paths:
      #     - path: /
      #       pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          # - metaphor.gitopsmagic.com
          - metaphor-london.gitopsmagic.com
  metaphor:
    host: https://metaphor-london.gitopsmagic.com/api
    console: https://kubefirst.gitopsmagic.com
  
  useExternalSecret: false
  configs:
    configOne: london-cluster-override-one
    configTwo: london-cluster-override-two
