apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: south-linkerd-control-plane-wait
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate
    path: 2024-austin/registry-test/clusters/south/linkerd-control-plane/wait
    targetRevision: east-west
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
