apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denver-cloudflare-origin-issuer-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cloudflare/origin-ca-issuer
    path: deploy/crds
    targetRevision: v0.6.1
  destination:
    name: denver
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true