apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-eso
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-eso
  namespace: linkerd
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-eso
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-eso
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-eso
    namespace: linkerd
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-linkerd-identity
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=identity
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-proxy-injector
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=proxy-injector
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-destination
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - linkerd
            - --label
            - app.kubernetes.io/name=destination
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
