apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denver-linkerd-control-plane-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '35'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate
    path: 2024-austin/registry-backup/clusters/denver/linkerd-control-plane-wait
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
