apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denver-external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.3
    helm:
      releaseName: external-dns
      values: |
        serviceAccount:
          create: true
          name: external-dns
        provider: civo
        sources:
        - ingress
        domainFilters:
        - kubefast.com
        env:
        - name: CIVO_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns-secrets
              key: token
        # extraArgs:
        # - --txt-owner-id=denver
        # - --txt-prefix=denver.
    chart: external-dns
  destination:
    name: denver
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
