apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: dublin-infrastructure
spec:
  providerConfigRef: 
    name: dublin
  forProvider:
    source: Remote
    module: git::https://github.com/kubefirst/navigate.git//2024-austin/terraform/modules/cluster-cloudflare?ref=main
    vars:
    - key: cluster_name
      value: dublin
    - key: node_count
      value: "3"
    - key: node_type
      value: "g4s.kube.medium"
