apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-london-linkerd-multicluster-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate
    path: 2024-austin/registry/clusters/cluster-london/linkerd/components/multicluster
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
