apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: west-linkerd-smi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    chart: linkerd-smi
    repoURL: https://linkerd.github.io/linkerd-smi
    targetRevision: linkerd-smi-1.0.4
  destination:
    name: west
    namespace: linkerd-smi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
