apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: east-cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: 2024-austin/registry-test/clusters/east/cert-issuers
    targetRevision: east-west
  destination:
    name: east
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
